# Generated by Django 5.2.6 on 2025-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwAuditLogs',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('action_time', models.DateTimeField()),
                ('actor', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'vw_audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwCars',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('make_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('seller_username', models.CharField(max_length=150, null=True)),
                ('seller_email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'vw_cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwOrders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=17)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('make_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('buyer_username', models.CharField(max_length=150, null=True)),
                ('buyer_email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'vw_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwReviews',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('reviewer_username', models.CharField(max_length=150)),
                ('reviewed_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'vw_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwTransactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_status', models.CharField(max_length=20)),
                ('order_id', models.IntegerField()),
                ('buyer_username', models.CharField(max_length=150, null=True)),
                ('car_vin', models.CharField(max_length=17)),
                ('make_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwUserRoles',
            fields=[
                ('user_role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vw_user_roles',
                'managed': False,
            },
        ),
    ]
