# Generated by Django 5.2.6 on 2025-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-action_time']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-action_time'], name='core_auditl_action__d5c966_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name'], name='core_auditl_table_n_4a8950_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
    ]
