# Generated by Django 5.2.6 on 2025-09-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vwauditlogs_vwcars_vworders_vwreviews_vwtransactions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VwAuditLogs',
        ),
        migrations.DeleteModel(
            name='VwCars',
        ),
        migrations.DeleteModel(
            name='VwOrders',
        ),
        migrations.DeleteModel(
            name='VwReviews',
        ),
        migrations.DeleteModel(
            name='VwTransactions',
        ),
        migrations.DeleteModel(
            name='VwUserRoles',
        ),
    ]
