# Generated by Django 5.2.6 on 2025-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_auditlog_action_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
