# Generated by Django 5.2.6 on 2025-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_vwauditlogs_delete_vwcars_delete_vworders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
