# Generated by Django 5.2.6 on 2025-09-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image',
            field=models.ImageField(default='car_images/default.png', upload_to='car_images/'),
        ),
    ]
