# Generated by Django 5.2.6 on 2025-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_model_name_model_uniq_model_per_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
