# Generated by Django 5.2.6 on 2025-09-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_procs_triggers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='car_price_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='car_year_range',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='uniq_car_vin',
        ),
    ]
