# Generated by Django 5.2.6 on 2025-09-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sp_cancel_reservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='car',
            name='car_price_gt_zero_v2',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='car_year_range_v2',
        ),
    ]
