# Generated by Django 5.2.6 on 2025-09-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_car_car_price_gt_zero_v2_and_more'),
        ('core', '0015_usersettings'),
    ]

    operations = [
    ]
