# Generated by Django 5.2.6 on 2025-09-24 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250924_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD.MM.YYYY', 'DD.MM.YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='DD.MM.YYYY', max_length=12)),
                ('number_format', models.CharField(choices=[('1 234,56', '1 234,56'), ('1,234.56', '1,234.56')], default='1 234,56', max_length=12)),
                ('page_size', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)])),
                ('saved_filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        check=(models.Q(page_size__gte=5) & models.Q(page_size__lte=200)),
                        name='usersettings_page_size_range',
                    ),
                ],
            },
        ),
    ]
