# Generated by Django 5.2.6 on 2025-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_backupfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('scheduler_enabled', models.BooleanField(default=False)),
                ('cron', models.CharField(default='0 3 * * *', max_length=64)),
                ('retention_days', models.PositiveIntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки бэкапов',
                'verbose_name_plural': 'Настройки бэкапов',
            },
        ),
    ]
