# Generated by Django 5.2.6 on 2025-09-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_backupconfig_last_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
