# Generated by Django 5.2.6 on 2025-09-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_backupconfig_last_run_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupconfig',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='retention_days',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='scheduler_enabled',
        ),
        migrations.RemoveField(
            model_name='backupconfig',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='last_run_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
