# Generated by Django 5.2.6 on 2025-10-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_usersettings_theme_default_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='core.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_favorite',
                'indexes': [models.Index(fields=['user'], name='core_favori_user_id_cbe902_idx'), models.Index(fields=['car'], name='core_favori_car_id_1ad79f_idx')],
                'unique_together': {('user', 'car')},
            },
        ),
    ]
