
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pytest-cov
      - name: Run API tests (expects running API env)
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          ANALYST_TOKEN: ${{ secrets.ANALYST_TOKEN }}
        run: |
          cd test_artifacts
          mkdir -p reports
          pytest -q || true
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: test_artifacts/reports
