BEGIN;
--
-- Create model Car
--
CREATE TABLE "core_car" ("VIN" varchar(17) NOT NULL PRIMARY KEY, "year" integer NOT NULL, "price" numeric(12, 2) NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Make
--
CREATE TABLE "core_make" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE);
--
-- Create model Role
--
CREATE TABLE "core_role" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE);
--
-- Create model CarImage
--
CREATE TABLE "core_carimage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image_url" varchar(200) NOT NULL, "car_id" varchar(17) NOT NULL);
--
-- Add field make to car
--
ALTER TABLE "core_car" ADD COLUMN "make_id" bigint NOT NULL CONSTRAINT "core_car_make_id_dad62edd_fk_core_make_id" REFERENCES "core_make"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_car_make_id_dad62edd_fk_core_make_id" IMMEDIATE;
--
-- Create model Model
--
CREATE TABLE "core_model" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE, "make_id" bigint NOT NULL);
--
-- Add field model to car
--
ALTER TABLE "core_car" ADD COLUMN "model_id" bigint NOT NULL CONSTRAINT "core_car_model_id_ab210b11_fk_core_model_id" REFERENCES "core_model"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_car_model_id_ab210b11_fk_core_model_id" IMMEDIATE;
--
-- Create model Order
--
CREATE TABLE "core_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order_date" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "car_id" varchar(17) NOT NULL);
--
-- Create model Transaction
--
CREATE TABLE "core_transaction" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "amount" numeric(12, 2) NOT NULL, "transaction_date" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "order_id" bigint NOT NULL);
--
-- Create model User
--
CREATE TABLE "core_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "core_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "core_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Review
--
CREATE TABLE "core_review" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rating" smallint NOT NULL CHECK ("rating" >= 0), "comment" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "reviewed_user_id" bigint NOT NULL, "reviewer_id" bigint NOT NULL);
--
-- Add field buyer to order
--
ALTER TABLE "core_order" ADD COLUMN "buyer_id" bigint NULL CONSTRAINT "core_order_buyer_id_75e0ab1b_fk_core_user_id" REFERENCES "core_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_order_buyer_id_75e0ab1b_fk_core_user_id" IMMEDIATE;
--
-- Add field seller to car
--
ALTER TABLE "core_car" ADD COLUMN "seller_id" bigint NULL CONSTRAINT "core_car_seller_id_f28e3cc5_fk_core_user_id" REFERENCES "core_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_car_seller_id_f28e3cc5_fk_core_user_id" IMMEDIATE;
--
-- Create model AuditLog
--
CREATE TABLE "core_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(100) NOT NULL, "table_name" varchar(50) NOT NULL, "record_id" integer NULL, "old_data" 
jsonb NULL, "new_data" jsonb NULL, "action_time" timestamp with time zone NOT NULL, "user_id" bigint NULL);
--
-- Create model UserRole
--
CREATE TABLE "core_userrole" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "role_id" bigint NOT NULL, "user_id" bigint NOT NULL);
CREATE INDEX "core_car_VIN_59031950_like" ON "core_car" ("VIN" varchar_pattern_ops);
CREATE INDEX "core_make_name_07f7e019_like" ON "core_make" ("name" varchar_pattern_ops);
CREATE INDEX "core_role_name_ca4cd9c7_like" ON "core_role" ("name" varchar_pattern_ops);
ALTER TABLE "core_carimage" ADD CONSTRAINT "core_carimage_car_id_980997b9_fk_core_car_VIN" FOREIGN KEY ("car_id") REFERENCES "core_car" ("VIN") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_carimage_car_id_980997b9" ON "core_carimage" ("car_id");
CREATE INDEX "core_carimage_car_id_980997b9_like" ON "core_carimage" ("car_id" varchar_pattern_ops);
CREATE INDEX "core_car_make_id_dad62edd" ON "core_car" ("make_id");
ALTER TABLE "core_model" ADD CONSTRAINT "core_model_make_id_dafc45de_fk_core_make_id" FOREIGN KEY ("make_id") REFERENCES "core_make" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_model_name_f7c87d81_like" ON "core_model" ("name" varchar_pattern_ops);
CREATE INDEX "core_model_make_id_dafc45de" ON "core_model" ("make_id");
CREATE INDEX "core_car_model_id_ab210b11" ON "core_car" ("model_id");
ALTER TABLE "core_order" ADD CONSTRAINT "core_order_car_id_5e0a257c_fk_core_car_VIN" FOREIGN KEY ("car_id") REFERENCES "core_car" ("VIN") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_order_car_id_5e0a257c" ON "core_order" ("car_id");
CREATE INDEX "core_order_car_id_5e0a257c_like" ON "core_order" ("car_id" varchar_pattern_ops);
ALTER TABLE "core_transaction" ADD CONSTRAINT "core_transaction_order_id_e41a6bc5_fk_core_order_id" FOREIGN KEY ("order_id") REFERENCES "core_order" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_transaction_order_id_e41a6bc5" ON "core_transaction" ("order_id");
CREATE INDEX "core_user_username_36e4f7f7_like" ON "core_user" ("username" varchar_pattern_ops);
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_group_id_c82fcad1_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_user_id_70b4d9b8_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_groups" ADD CONSTRAINT "core_user_groups_group_id_fe8c697f_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_groups_user_id_70b4d9b8" ON "core_user_groups" ("user_id");
CREATE INDEX "core_user_groups_group_id_fe8c697f" ON "core_user_groups" ("group_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_permission_id_73ea0daa_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permissions_user_id_085123d3_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_user_user_permissions" ADD CONSTRAINT "core_user_user_permi_permission_id_35ccf601_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_user_user_permissions_user_id_085123d3" ON "core_user_user_permissions" ("user_id");
CREATE INDEX "core_user_user_permissions_permission_id_35ccf601" ON "core_user_user_permissions" ("permission_id");
ALTER TABLE "core_review" ADD CONSTRAINT "core_review_reviewed_user_id_bf86514c_fk_core_user_id" FOREIGN KEY ("reviewed_user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_review" ADD CONSTRAINT "core_review_reviewer_id_b24f930d_fk_core_user_id" FOREIGN KEY ("reviewer_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_review_reviewed_user_id_bf86514c" ON "core_review" ("reviewed_user_id");
CREATE INDEX "core_review_reviewer_id_b24f930d" ON "core_review" ("reviewer_id");
CREATE INDEX "core_order_buyer_id_75e0ab1b" ON "core_order" ("buyer_id");
CREATE INDEX "core_car_seller_id_f28e3cc5" ON "core_car" ("seller_id");
ALTER TABLE "core_auditlog" ADD CONSTRAINT "core_auditlog_user_id_3797aaab_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_auditlog_user_id_3797aaab" ON "core_auditlog" ("user_id");
ALTER TABLE "core_userrole" ADD CONSTRAINT "core_userrole_role_id_8272b20d_fk_core_role_id" FOREIGN KEY ("role_id") REFERENCES "core_role" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_userrole" ADD CONSTRAINT "core_userrole_user_id_aca63c51_fk_core_user_id" FOREIGN KEY ("user_id") REFERENCES "core_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_userrole_role_id_8272b20d" ON "core_userrole" ("role_id");
CREATE INDEX "core_userrole_user_id_aca63c51" ON "core_userrole" ("user_id");
COMMIT;